### ISSUE TITLE
Add more options

### ISSUE THREAD

**Issue by nikymorg** [learn-co-curriculum/oo-relationships-practice#1]
- band - concert - venue
- traveler - ticket - destination
- actor - appearance - movie
- employer - job - employee
- investor - stock - company
- donor - donation - charity

**Comment by nikymorg** [comment]
- Created basic relationships for concert and investment domains.
- Need extra methods for concert and investment domains.
- Employment domain might be too abstract to understand.

**Comment by maxcell** [comment]
@nikymorg These are incredible!

**Comment by sgharms** [comment]
@nikymorg @maxcell Is there anything actionable on this issue? It looks like it was re-opened by Prince throwing shout-outs, but I don't want to close prematurely? Knowing you're busy and it seems like these ideas were merged in, I'm going to close. LMK via slack if I erred.
