### ISSUE TITLE
IMDB methods

### ISSUE THREAD

**Issue by Nat-Reid** [learn-co-curriculum/oo-relationships-practice#4]
imdb Character most_appearances method should be a class method, and Show on_the_big_screen method should read "should return Movies that share the same name as this Show"

-Steven ok'd

**Comment by RylanBauermeister** [comment]
This is still true, and relevant.

**Comment by maxwellbenton** [comment]
Hi @Nat-Reid,

Thank you for spotting this and providing feedback. We've updated this lesson and have incorporated these changes, which should resolve this issue.

Thank you for contributing to a Learn lesson!
